server.port=8080
spring.application.name=vehiculos-api

# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://mariajrodrigueza_db_user:ICvKn0pIIwkjHZeu@cluster0.9i5mpfv.mongodb.net/vehiculos_db?retryWrites=true&w=majority&appName=Cluster0

# Logging
logging.level.root=INFO
logging.level.com.vehiculos=DEBUG

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html