spring:
  application:
    name: automotriz

  data:
    mongodb:
      uri: "mongodb+srv://mariajrodrigueza_db_user:ICvKn0pIIwkjHZeu@cluster0.9i5mpfv.mongodb.net/automotriz?retryWrites=true&w=majority"
      database: automotriz

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 9090
  servlet:
    context-path: /api/v2

logging:
  level:
    root: INFO
    com.automotriz: DEBUG
    org.springframework.data.mongodb: DEBUG
